//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "charts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub ticker: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub open: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub high: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub low: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub close: Option<f64>,
    pub volume: Option<i32>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub datetime: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
