//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "daily_cap")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub ticker: String,
    pub market_cap: Option<i64>,
    pub trading_volume: Option<i64>,
    pub change: Option<Decimal>,
    pub datetime: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
