//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "trading_volume")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub ticker: String,
    pub inst_sum: Option<Decimal>,
    pub etc_corp: Option<i32>,
    pub individual: Option<i32>,
    pub foreigner: Option<i32>,
    pub total: Option<i32>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub datetime: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
